// pages/PrivacyPage.jsx — Privacy Policy

import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import Navbar from '../components/Navbar'
import SEO from '../components/SEO'

const EASE = [0.22, 1, 0.36, 1]

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'var(--navy-950)' }}>
      <SEO title="Privacy Policy" path="/privacy" />
      <Navbar />
      <main style={{ maxWidth: '720px', margin: '0 auto', padding: '48px 24px 100px' }}>
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, ease: EASE }}>

          <Link to="/" style={{ color: 'var(--text-secondary)', fontSize: '0.82rem', textDecoration: 'none', display: 'inline-block', marginBottom: '32px' }}>
            ← Home
          </Link>

          <h1 style={{ fontSize: 'clamp(1.6rem, 4vw, 2rem)', fontWeight: 800, letterSpacing: '-0.035em', color: 'var(--text-primary)', margin: '0 0 8px' }}>
            Privacy Policy
          </h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', margin: '0 0 48px' }}>
            Last updated: June 2026
          </p>

          <LegalSection title="1. What We Collect">
            When you use CVOptimize, we may collect the following information:
            <ul style={{ marginTop: '10px', paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <li><strong style={{ color: 'var(--text-primary)' }}>Account information</strong> — your email address and display name when you register</li>
              <li><strong style={{ color: 'var(--text-primary)' }}>Resume content</strong> — text extracted from PDF or DOCX files you upload, stored to enable saved resume features</li>
              <li><strong style={{ color: 'var(--text-primary)' }}>Job descriptions</strong> — text you paste into the Job Match tool, stored with your analysis history</li>
              <li><strong style={{ color: 'var(--text-primary)' }}>Analysis results</strong> — fit scores, matched skills, gaps, and improvement findings generated by AI, stored to power your history</li>
            </ul>
            <p style={{ marginTop: '12px' }}>We do not collect payment information, location data, or browsing behaviour beyond what is described above.</p>
          </LegalSection>

          <LegalSection title="2. How We Use It">
            We use the information we collect to:
            <ul style={{ marginTop: '10px', paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <li>Provide the core functionality of the Service (resume analysis, improvement suggestions)</li>
              <li>Show you your saved resumes and analysis history</li>
              <li>Allow you to manage your account and preferences</li>
            </ul>
            <p style={{ marginTop: '12px' }}>We do not sell, rent, or share your personal data with third parties for marketing or advertising purposes.</p>
          </LegalSection>

          <LegalSection title="3. AI Processing">
            To generate analysis results, your resume text and job description are sent to the <strong style={{ color: 'var(--text-primary)' }}>Google Gemini API</strong>. This means your content is subject to Google's data processing terms and privacy policy in addition to ours. We do not use your resume content to train our own models. Google may process this data in accordance with their API usage policies.
          </LegalSection>

          <LegalSection title="4. Cookies">
            We use a single <strong style={{ color: 'var(--text-primary)' }}>httpOnly JWT cookie</strong> to keep you signed in across sessions. This cookie cannot be read by JavaScript and is not used for tracking. We do not use third-party advertising cookies, analytics cookies, or any form of cross-site tracking.
          </LegalSection>

          <LegalSection title="5. Data Retention">
            Your data is retained for as long as your account exists. When you delete your account via the Account settings page, all associated data — including your saved resumes, analysis history, and account information — is permanently and immediately deleted from our database.
          </LegalSection>

          <LegalSection title="6. Your Rights">
            You have the right to:
            <ul style={{ marginTop: '10px', paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <li><strong style={{ color: 'var(--text-primary)' }}>Access</strong> — view all data associated with your account</li>
              <li><strong style={{ color: 'var(--text-primary)' }}>Correct</strong> — update your name and email via the Account settings page</li>
              <li><strong style={{ color: 'var(--text-primary)' }}>Delete</strong> — permanently delete your account and all data at any time</li>
            </ul>
            <p style={{ marginTop: '12px' }}>All of these actions are available directly from your{' '}
              <Link to="/account" style={{ color: 'var(--accent)', textDecoration: 'none' }}>Account settings</Link> page.
            </p>
          </LegalSection>

          <LegalSection title="7. Security">
            We take reasonable precautions to protect your data:
            <ul style={{ marginTop: '10px', paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <li>Passwords are hashed using <strong style={{ color: 'var(--text-primary)' }}>bcrypt</strong> — we never store plain-text passwords</li>
              <li>Authentication tokens are stored in <strong style={{ color: 'var(--text-primary)' }}>httpOnly cookies</strong>, protecting against XSS attacks</li>
              <li>All communication is over <strong style={{ color: 'var(--text-primary)' }}>HTTPS</strong> in production</li>
            </ul>
            <p style={{ marginTop: '12px' }}>No method of transmission over the internet is 100% secure. We cannot guarantee absolute security of your data.</p>
          </LegalSection>

          <LegalSection title="8. Children">
            CVOptimize is not intended for use by individuals under the age of 13. We do not knowingly collect personal information from children under 13. If you believe a child has provided us with personal information, please contact us so we can delete it.
          </LegalSection>

          <LegalSection title="9. Affiliate Links">
            Some pages (such as your analysis results) may contain <strong style={{ color: 'var(--text-primary)' }}>affiliate links</strong> to third-party products and services we think may help your job search. If you click one and make a purchase, we may earn a commission at no extra cost to you. These links are clearly labelled, and we only recommend services relevant to resumes and careers. We do not share your personal data with these third parties.
          </LegalSection>

          <LegalSection title="10. Changes to This Policy">
            We may update this Privacy Policy from time to time. We will indicate the date of the most recent update at the top of this page. Your continued use of the Service after changes are posted constitutes your acceptance of the updated policy.
          </LegalSection>

          <LegalSection title="11. Contact">
            If you have any questions or concerns about this Privacy Policy or your data, please open an issue on our{' '}
            <a href="https://github.com" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent)', textDecoration: 'none' }}>GitHub repository</a>.
          </LegalSection>

        </motion.div>
      </main>
    </div>
  )
}

function LegalSection({ title, children }) {
  return (
    <div style={{ marginBottom: '36px' }}>
      <h2 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)', margin: '0 0 12px', letterSpacing: '-0.01em' }}>
        {title}
      </h2>
      <div style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.75 }}>
        {children}
      </div>
    </div>
  )
}
