// pages/TermsPage.jsx — Terms of Service

import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import Navbar from '../components/Navbar'
import SEO from '../components/SEO'

const EASE = [0.22, 1, 0.36, 1]

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'var(--navy-950)' }}>
      <SEO title="Terms of Service" path="/terms" />
      <Navbar />
      <main style={{ maxWidth: '720px', margin: '0 auto', padding: '48px 24px 100px' }}>
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, ease: EASE }}>

          <Link to="/" style={{ color: 'var(--text-secondary)', fontSize: '0.82rem', textDecoration: 'none', display: 'inline-block', marginBottom: '32px' }}>
            ← Home
          </Link>

          <h1 style={{ fontSize: 'clamp(1.6rem, 4vw, 2rem)', fontWeight: 800, letterSpacing: '-0.035em', color: 'var(--text-primary)', margin: '0 0 8px' }}>
            Terms of Service
          </h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', margin: '0 0 48px' }}>
            Last updated: April 2026
          </p>

          <LegalSection title="1. Acceptance of Terms">
            By accessing or using CVOptimize ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
          </LegalSection>

          <LegalSection title="2. Description of Service">
            CVOptimize is a free, AI-powered resume analysis tool that helps users compare their resumes against job descriptions, receive improvement suggestions, and track their application readiness over time. The Service is provided free of charge and is intended for personal, non-commercial use.
          </LegalSection>

          <LegalSection title="3. User Accounts">
            You may use certain features of the Service without an account. To access saved history and personalised features, you must create an account with a valid email address and password. You are responsible for maintaining the confidentiality of your credentials and for all activity that occurs under your account. You must be at least 13 years old to use the Service.
          </LegalSection>

          <LegalSection title="4. Acceptable Use">
            You agree not to:
            <ul style={{ marginTop: '10px', paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorised access to any part of the Service or its infrastructure</li>
              <li>Scrape, crawl, or automate requests to the Service</li>
              <li>Impersonate any person or entity</li>
              <li>Upload content that contains malware, viruses, or any other harmful code</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
            </ul>
          </LegalSection>

          <LegalSection title="5. AI-Generated Content">
            The Service uses artificial intelligence (Google Gemini) to analyse resumes and job descriptions. AI-generated results are provided for informational purposes only and are not a substitute for professional career advice. CVOptimize makes no guarantees about the accuracy, completeness, or suitability of any AI-generated output. Do not make significant career decisions based solely on AI analysis.
          </LegalSection>

          <LegalSection title="6. Your Data">
            When you use the Service, your resume content and job descriptions are processed by Google's Gemini AI API to generate analysis results. Analysis results and account information are stored in our database to provide your history and personalised features. We do not sell your data to third parties. For full details on how we handle your data, please see our{' '}
            <Link to="/privacy" style={{ color: 'var(--accent)', textDecoration: 'none' }}>Privacy Policy</Link>.
          </LegalSection>

          <LegalSection title="7. Intellectual Property">
            You retain full ownership of any resume content or other materials you upload. CVOptimize retains ownership of its software, design, branding, and AI analysis outputs generated by the Service. You may not reproduce, distribute, or create derivative works of the Service's interface or code without express written permission.
          </LegalSection>

          <LegalSection title="8. Termination">
            We reserve the right to suspend or terminate your account at any time if we reasonably believe you have violated these Terms of Service, without prior notice. You may delete your account at any time via the Account settings page, which will permanently remove all your data.
          </LegalSection>

          <LegalSection title="9. Disclaimer of Warranties">
            The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. CVOptimize does not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components. Use of the Service is at your own risk.
          </LegalSection>

          <LegalSection title="10. Limitation of Liability">
            To the fullest extent permitted by law, CVOptimize and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, the Service — including any career decisions made in reliance on AI-generated output.
          </LegalSection>

          <LegalSection title="11. Changes to Terms">
            We may update these Terms of Service from time to time. We will indicate the date of the most recent update at the top of this page. Continued use of the Service after changes are posted constitutes your acceptance of the updated terms.
          </LegalSection>

          <LegalSection title="12. Contact">
            If you have any questions about these Terms, please open an issue on our{' '}
            <a href="https://github.com" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent)', textDecoration: 'none' }}>GitHub repository</a>.
          </LegalSection>

        </motion.div>
      </main>
    </div>
  )
}

function LegalSection({ title, children }) {
  return (
    <div style={{ marginBottom: '36px' }}>
      <h2 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)', margin: '0 0 12px', letterSpacing: '-0.01em' }}>
        {title}
      </h2>
      <div style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.75 }}>
        {children}
      </div>
    </div>
  )
}
