"""Add job_title to analyses

Revision ID: 05700db7a478
Revises: 382a3aba990d
Create Date: 2026-04-07 21:16:17.919373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05700db7a478'
down_revision = '382a3aba990d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
