"""Add strengths and gaps to analyses

Revision ID: 382a3aba990d
Revises: e9c3cabce215
Create Date: 2026-04-07 13:20:59.952877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382a3aba990d'
down_revision = 'e9c3cabce215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strengths', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('gaps', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('gaps')
        batch_op.drop_column('strengths')

    # ### end Alembic commands ###
