"""add verification token to users

Revision ID: b4851cf2081e
Revises: bedfdd8b556c
Create Date: 2026-04-08 16:13:21.635972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4851cf2081e'
down_revision = 'bedfdd8b556c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_verification_token'), ['verification_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_verification_token'))
        batch_op.drop_column('verification_token_expires')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
